# File: config/main.toml

# Server settings
host = "0.0.0.0"
port = 8095

# Monitoring settings
check_interval_seconds = 90
rpc_timeout_seconds = 10
alarm_webhook_url = "https://n8n-hooks.kostovster.io/nodes"

# Hermes settings
hermes_min_uptime_minutes = 5

auto_restore_trigger_words = [
    "Block.Header.AppHash",
    "Block.Header.LastResultsHash"
]
