# File: config/discovery.toml

[server]
host = "192.168.11.206"
ssh_key_path = "/Users/kostovster/.ssh/n8n_ssh"
ssh_username = "root"
max_concurrent_ssh = 5
ssh_timeout_seconds = 30

[nodes.osmosis-1]
rpc_url = "http://192.168.11.206:26685"
network = "osmosis-1"
server_host = "discovery"
enabled = true
# pruning_enabled = true
# pruning_schedule = "0 0 12 * * 2"  # Tuesdays at 12:00
# pruning_keep_blocks = 8000
# pruning_keep_versions = 8000
# pruning_deploy_path = "/opt/deploy/osmosis"
# pruning_service_name = "osmosis"

[nodes.neutron-1]
rpc_url = "http://192.168.11.206:26692"
network = "neutron-1"
server_host = "discovery"
enabled = true
# pruning_enabled = true
# pruning_schedule = "0 0 14 * * 2"  # Tuesdays at 14:00
# pruning_keep_blocks = 8000
# pruning_keep_versions = 8000
# pruning_deploy_path = "/opt/deploy/neutron"
# pruning_service_name = "neutron"

# [hermes.relay-discovery]
# server_host = "discovery"
# service_name = "hermes"
# log_path = "/var/log/hermes"
# restart_schedule = "0 0 16 * * 2"  # Tuesdays at 16:00
# dependent_nodes = ["discovery-osmosis-1", "discovery-neutron-1"]
