# File: config/main.toml

# Server settings
host = "0.0.0.0"
port = 8095

# Monitoring settings
check_interval_seconds = 90
rpc_timeout_seconds = 10
alarm_webhook_url = "http://your-n8n-instance/webhook/node-alarm"

# Hermes settings
hermes_min_uptime_minutes = 5
